# Generated by Django 4.0.4 on 2022-05-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_18_29', models.IntegerField(max_length=8)),
                ('age_30_50', models.IntegerField(max_length=8)),
                ('age_51', models.IntegerField(max_length=8)),
            ],
        ),
    ]
