# Generated by Django 4.0.4 on 2022-05-28 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_api', '0012_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='sex',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.FloatField(max_length=3)),
                ('degree', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='general_api.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
