# Generated by Django 4.0.4 on 2022-05-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0013_employeeprofile_sex_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='name',
        ),
    ]
