# Generated by Django 4.0.4 on 2022-05-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0014_rename_job_name_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
