# Generated by Django 4.0.4 on 2022-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_api', '0015_application_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
